package verificationClasses;

import tests.MineTEST;

public class FeatureSwitches {
	/*

 * DO NOT EDIT! THIS FILE IS AUTOGENERATED BY fstcomp 
public static String getSelectedFeaturesAsNames() {
StringBuilder sb = new StringBuilder();
	if (MineTEST.__SELECTED_FEATURE_methaneQuery) sb.append("methaneQuery;");
	if (MineTEST.__SELECTED_FEATURE_lowWaterSensor) sb.append("lowWaterSensor;");
	if (MineTEST.__SELECTED_FEATURE_base) sb.append("base;");
	if (MineTEST.__SELECTED_FEATURE_stopCommand) sb.append("stopCommand;");
	if (MineTEST.__SELECTED_FEATURE_startCommand) sb.append("startCommand;");
	if (MineTEST.__SELECTED_FEATURE_methaneAlarm) sb.append("methaneAlarm;");
	if (MineTEST.__SELECTED_FEATURE_highWaterSensor) sb.append("highWaterSensor;");
return sb.toString();
}
public static void select_features() {
	MineTEST.__SELECTED_FEATURE_methaneQuery = verificationClasses.SPLModelChecker.getBoolean();
	MineTEST.__SELECTED_FEATURE_lowWaterSensor = verificationClasses.SPLModelChecker.getBoolean();
	MineTEST.__SELECTED_FEATURE_base = verificationClasses.SPLModelChecker.getBoolean();
	MineTEST.__SELECTED_FEATURE_stopCommand = verificationClasses.SPLModelChecker.getBoolean();
	MineTEST.__SELECTED_FEATURE_startCommand = verificationClasses.SPLModelChecker.getBoolean();
	MineTEST.__SELECTED_FEATURE_methaneAlarm = verificationClasses.SPLModelChecker.getBoolean();
	MineTEST.__SELECTED_FEATURE_highWaterSensor = verificationClasses.SPLModelChecker.getBoolean();
}

public static boolean __GUIDSL_ROOT_PRODUCTION;

public static void select_helpers() {
	__GUIDSL_ROOT_PRODUCTION = true;
}

public static boolean valid_product() {
	if (( MineTEST.__SELECTED_FEATURE_base ))
		return true;
	else
		return false;
} */
}